#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:

apt-get update
apt-get install -y haproxy

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 140674-web-01 54.172.58.212:80 check
        server 140674-web-02 18.207.2.170:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
