#!/usr/bin/env bash
# fix Ubuntu container's to listen on port 80
apt-get update
apt-get -y install curl
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
